spring:
  profiles: 
    active: local
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  freemarker:
    enabled: true
    suffix: .html
    request-context-attribute: rc
    content-type: text/html
    charset: UTF-8 #编码格式
  messages:
#    basename: i18n/messages
    cache-seconds: 3600
    
  mvc: 
    throw-exception-if-no-handler-found: true #出现错误时, 直接抛出异常

    
##################### DB #####################
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT user()
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    connection-properties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
            
management:
  security:
    enabled: false

endpoints: 
  health: 
    sensitive: false
    

mybatis: 
  configLocation: classpath:mybatis-config.xml
  
  
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env
    
  

    
