server: 
  port: 6180
spring:
##################### DB #####################
  datasource: 
    url: jdbc:mysql://123.207.54.159:3306/micro-req?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Mysql7456321.
    
        
logging: 
  config: classpath:log4j2-dev.xml
  
swagger: 
  enable: true

unified: 
  applicationCode: MicroUser

gateway: 
  url: http://localhost:53010
  clientId: web-user-admin
  clientSecret: 123456