server: 
  port: 53030
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:53000/eureka/

spring:
##################### DB #####################
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/micro-req?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 1122
    

            
logging: 
  config: classpath:log4j2-dev.xml
  
swagger: 
  enable: true


